Isics\Bundle\OpenMiamMiamBundle\Entity\Article:
    properties:
        title:
            - NotNull: ~
            - Length:
                max: 128
        body:
            - NotBlank: ~
        isPublished:
            - Type: bool
