Isics\Bundle\OpenMiamMiamBundle\Model\Association\AssociationWithOwner:
    properties:
        association:
            - Valid: ~
        owner:
            - NotNull:
                message: error.notfound
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Entity\Association:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotNull: ~
            - Length:
                max: 128
        closingDelay:
            - NotNull: ~
            - Range:
                min: 0
        openingDelay:
            - NotNull: ~
            - Range:
                min: 0
        defaultCommission:
            - NotNull: ~
            - Range:
                min: 0
                max: 100
        address1:
            - Length:
                max: 64
        address2:
            - Length:
                max: 64
        zipcode:
            - Length:
                max: 8
        city:
            - Length:
                max:  64
        phoneNumber1:
            - Length:
                max: 16
        phoneNumber2:
            - Length:
                max: 16
        website:
            - Url: ~
        facebook:
            - Url: ~
        email:
            - NotNull: ~
            - Email: ~
