Isics\Bundle\OpenMiamMiamBundle\Entity\Branch:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [city]
    properties:
        address1:
            - Length:
                max: 64
        address2:
            - Length:
                max: 64
        zipcode:
            - Length:
                max: 8
        city:
            - Length:
                max:  64
        departmentNumber:
            - NotNull: ~
            - Length:
                max: 2
        phoneNumber1:
            - Length:
                max: 16
        phoneNumber2:
            - Length:
                max: 16
        website:
            - Url: ~
        facebook:
            - Url: ~