Isics\Bundle\OpenMiamMiamBundle\Entity\Payment:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\Payment: ~
    properties:
        amount:
            - NotNull: ~
            - Range:
                min: 0
        type:
            - Choice: { callback: getTypes }

Isics\Bundle\OpenMiamMiamBundle\Entity\PaymentAllocation:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\PaymentAllocation: ~
    properties:
        amount:
            - NotNull: ~
            - Range:
                min: 0
