Isics\Bundle\OpenMiamMiamBundle\Model\Product\ArtificialProduct:
    properties:
        producer:
            - NotNull: ~
        price:
            - NotBlank: ~
            - Range:
                min: 0
        name:
            - NotBlank: ~

Isics\Bundle\OpenMiamMiamBundle\Entity\Product:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: [ref,producer]
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\Product: ~
    properties:
        name:
            - NotNull: ~
            - Length:
                max: 128
        ref:
            - NotNull: ~
            - Length:
                max: 16
        producer:
            - NotNull: ~
        category:
            - NotNull: ~
        isBio:
            - Type: bool
        isOfTheMoment:
            - Type: bool
        price:
            - Range:
                min: 0
        priceInfo:
            - Length:
                max: 128
        imageFile:
            - Image:
                maxSize: 5120k
        deleteImage:
            - Type: bool
        hasNoPrice:
            - Type: bool
        buyingUnit:
            - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\BuyingUnit: ~
        allowDecimalQuantity:
            - Type: bool
        availability:
            - Choice: { callback: getAvailabilityStatus}
        stock:
            - Type:
                type: numeric
        availableAt:
            - Date: ~
