Isics\Bundle\OpenMiamMiamBundle\Model\ProducerAttendance\ProducerAttendances:
    properties:
        branchAttendances:
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Model\ProducerAttendance\ProducerBranchAttendances:
    properties:
        branchOccurrenceAttendances:
            - Valid: ~

Isics\Bundle\OpenMiamMiamBundle\Model\ProducerAttendance\ProducerBranchOccurrenceAttendance:
    constraints:
        - Isics\Bundle\OpenMiamMiamBundle\Validator\Constraints\ProducerBranchOccurrenceAttendance: ~
    properties:
        producer:
            - NotNull: ~
        branchOccurrence:
            - NotNull: ~
        attendance:
            - Choice: { callback: getAttendancesStatus}
